server:
  port: 8084

spring:
  application:
    name: WALLET-SERVICE

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://3.128.171.66:30001/minet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Bootcamp@115!
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    mixed: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
